workflows:
    android-workflow:
        name: Android Budget Sign in
        max_build_duration: 120
        environment:
            flutter: stable
            groups:
                - google_play
            vars:
                PACKAGE_NAME: "com.devdesenvolvimento.budget"
                GOOGLE_PLAY_TRACK: alpha
            android_signing:
                - codemagic
        scripts:
            - name: Set up local.properties
              script: | 
                echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
            - name: Get Flutter packages
              script: | 
                flutter packages pub get
            - name: Build AAB with Flutter
              script: | 
                BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
                flutter build appbundle --release \
                  --build-name=1.0.$BUILD_NUMBER \
                  --build-number=$BUILD_NUMBER
        artifacts:
          - build/**/outputs/**/*.aab
          - build/**/outputs/**/mapping.txt
          - flutter_drive.log
        publishing:
            email:
                recipients:
                  - gabrieldnz12@outlook.com
            google_play:
                credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
                track: $GOOGLE_PLAY_TRACK
                submit_as_draft: true
    ios-workflow:
        name: iOS Workflow
        integrations:
          app_store_connect: Codemagic
        environment:
          ios_signing:
            distribution_type: app_store
            bundle_identifier: com.devdesenvolvimento.budget
          vars:
            BUNDLE_ID: "com.devdesenvolvimento.budget"
            XCODE_WORKSPACE: "Runner.xcworkspace" # <-- Put the name of your Xcode workspace here
            XCODE_SCHEME: "Runner" # <-- Put the name of your Xcode scheme here
            APP_STORE_APPLE_ID: 6451202221 # <-- Coloque o apple id do aplicativo em específico geral - informações do app - apple id
          xcode: latest
          cocoapods: default
        scripts:
            - script: keychain initialize
            - script: keychain add-certificates

            - script: xcode-project use-profiles
            - script: flutter packages pub get
            - name: Increment build number
              script: | 
                #!/bin/sh
                cd $CM_BUILD_DIR
                LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
                agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
            - name: Flutter build ipa and automatic versioning
              script: |
                flutter build ipa --export-options-plist=/Users/builder/export_options.plist
        artifacts: 
          - build/ios/ipa/*.ipa
        publishing: 
          email:
            recipients:
              - gabrieldnz12@outlook.com
          app_store_connect:
            auth: integration
    
            # Configuration related to TestFlight (optional)
            # Note: This action is performed during post-processing.
            submit_to_testflight: true
