workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
            flutter: stable
            android_signing:
                - keystore_reference
